# Use root/example as user/password credentials
version: "3.1"

services:
  app:
    build: .
    command: npm run start
    ports:
      - 5000:5000
  mongo:
    image: mongo:5
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
